key_words_params = [
    ("treatment", "prep", "#prep (hiv OR treatment)"),
    ("treatment", "prep", "#truvada OR truvada"),
    ("treatment", "prep", "#atripla OR atripla"),
    ("infection", "-", "#hivinfection OR (hiv infection)"),
    ("drug", "double dose", "#epzicom OR epzicom"),
    ("drug", "triple dose", "#complera OR complera"),
    ("treatment", "prep", "#ftc OR (ftc treatment) "),
    ("drug", "-", "#drug OR (drug hiv)"),
    ("infection", "-", "#hivtreatment OR hivtreatment OR (hiv treatment)"),
    ("drug", "triple dose", "(#3tc OR 3tc) (hiv OR treatment)"),
    ("drug", "triple dose", "#tripletherapy OR (triple therapy)"),
    ("infection", "-", "#anti OR anti (hiv OR treatment)"),
    ("drug", "antiretroviral", "#isentress OR isentress"),
    ("drug", "antiretroviral", "#reyataz OR reyataz"),
    ("drug", "antiretroviral", "#norvir OR norvir"),
    ("infection", "-", "#livingwithaids OR (living aids)"),
    ("infection", "-", "#NormalizingHIVChallenge OR (Normalizing HIV Challenge)"),
    ("drug", "antiretroviral", "#sustiva OR sustiva"),
    ("drug", "antiretroviral", "#stocrin OR stocrin"),
    ("infection", "-", "#viread OR viread"),
    ("treatment", "pep", "#pep (hiv OR treatment)"),
    ("treatment", "pep", "#pepforhiv OR (pep hiv)"),
    ("treatment", "pep", "#pepforearlyhiv OR (pep for early hiv) or (pep hiv)"),
    ("treatment", "pep", "#pepindelhi OR (pep delhi)"),
    ("treatment", "pep", "#peptreatment OR (pep treatment)"),
    ("hiv center", "-", "#peptreatmentinmalviyanagar or (pep treatment malviyanagar) OR (pep malviyanagar)"),
    ("hiv center", "-", "#pepcenterforhiv OR (pep center for hiv) "),
    ("hiv center", "-", "#pephivcenter OR (pep center hiv)"),
    ("infection", "-", "#pepforealryexposer OR (pep real exposer)"),
    ("treatment", "-", "#pepandprep OR (pep prep) OR ((pep OR prep) treatment)")
]
